### ISSUE TITLE
initial_setup.sh error while executing

### ISSUE THREAD

**Issue by dbavale** [Interceptera/Interceptera#2]
root@inter:/opt/interceptera/Interceptera-master# sh initial_setup.sh
initial_setup.sh: 7: initial_setup.sh: function: not found
Enter lan side ethernet adaptor name
eth1

Enter subnet range ea. 192.168.99 for /24
192.168.99

initial_setup.sh: 22: initial_setup.sh: Syntax error: "}" unexpected

**Comment by amcorp** [comment]
fuck you pay me
